language: bash
dist: xenial
services: docker
addons:
  apt:
    packages:
      - docker-ce
    update: true
env:
  - CPU=Xeon buildOS=centos-7.6 usage=analytics imageName=ffmpeg
  - CPU=Xeon buildOS=centos-7.6 usage=analytics imageName=gst
  - CPU=Xeon buildOS=centos-7.6 usage=media imageName=ffmpeg
  - CPU=Xeon buildOS=centos-7.6 usage=media imageName=gst
  - CPU=Xeon buildOS=centos-7.6 usage=media imageName=nginx
  - CPU=Xeon buildOS=centos-7.6 usage=graphics imageName=ospray
  - CPU=Xeon buildOS=centos-7.6 usage=graphics imageName=ospray-mpi
  - CPU=Xeon buildOS=centos-7.6 usage=service imageName=owt
  - CPU=Xeon buildOS=centos-7.6 usage=service imageName=owt-immersive
  - CPU=Xeon buildOS=centos-7.6 usage=media imageName=dev
  - CPU=Xeon buildOS=centos-7.6 usage=analytics imageName=dev
  - CPU=Xeon buildOS=centos-7.6 usage=graphics imageName=dev
  - CPU=Xeon buildOS=ubuntu-18.04 usage=analytics imageName=ffmpeg
  - CPU=Xeon buildOS=ubuntu-18.04 usage=analytics imageName=gst
  - CPU=Xeon buildOS=ubuntu-18.04 usage=media imageName=ffmpeg
  - CPU=Xeon buildOS=ubuntu-18.04 usage=media imageName=gst
  - CPU=Xeon buildOS=ubuntu-18.04 usage=media imageName=nginx
  - CPU=Xeon buildOS=ubuntu-18.04 usage=graphics imageName=ospray
  - CPU=Xeon buildOS=ubuntu-18.04 usage=graphics imageName=ospray-mpi
  - CPU=Xeon buildOS=ubuntu-18.04 usage=service imageName=owt
  - CPU=Xeon buildOS=ubuntu-18.04 usage=media imageName=dev
  - CPU=Xeon buildOS=ubuntu-18.04 usage=analytics imageName=dev
  - CPU=Xeon buildOS=ubuntu-18.04 usage=graphics imageName=dev

before_install:
  - docker version
script:
  - &basescript |
    mkdir build && cd build && cmake -DBUILD_MP3LAME=OFF -DBUILD_FDKAAC=OFF ..
    cd ${CPU}/${buildOS}/${usage}/${imageName}
  - make
  - travis_retry ctest -V

matrix:
  fast_finish: true
  allow_failures: # NGINX RTMP tests are not stable, gst analytics images and dev images run out of time
    - name: centos-7.6/dev
    - env: CPU=Xeon buildOS=centos-7.6 usage=media imageName=nginx
    - env: CPU=Xeon buildOS=centos-7.6 usage=analytics imageName=gst
    - env: CPU=Xeon buildOS=centos-7.6 usage=media imageName=dev
    - env: CPU=Xeon buildOS=centos-7.6 usage=analytics imageName=dev
    - env: CPU=Xeon buildOS=centos-7.6 usage=graphics imageName=dev
    - name: ubuntu-18.04/dev
    - env: CPU=Xeon buildOS=ubuntu-18.04 usage=media imageName=nginx
    - env: CPU=Xeon buildOS=ubuntu-18.04 usage=analytics imageName=gst
    - env: CPU=Xeon buildOS=ubuntu-18.04 usage=media imageName=dev
    - env: CPU=Xeon buildOS=ubuntu-18.04 usage=analytics imageName=dev
    - env: CPU=Xeon buildOS=ubuntu-18.04 usage=graphics imageName=dev
